### ISSUE TITLE
int logs

### ISSUE THREAD

**Issue by leyendecker** [opsxcq/consolelog#1]
if log is not a string, python server.py will throw an error (stack below)
`console.log(1)`

----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 51227)
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "server.py", line 34, in do_POST
    print("LOG: "+ data["data"])
TypeError: cannot concatenate 'str' and 'int' objects

**Comment by opsxcq** [comment]
Check commit ebee064224506e520bc6d8f006696083aeadea7b

**Comment by leyendecker** [comment]
tks for the fix.
